Studentersamfundets-Interne-Teater/sit-web

- .gitignore
Har fått satt opp utviklingsmiljø på maskina 👍
> Added local venv to gitignore

- SITnett/graphics/style.css
- SITnett/templates/hoved.html
- SITnett/templates/meny.html
Sjekker samtidig om vi har støtte for gifs i PR'er. Hvis ikke skal jeg få fikset det. ![image](https://media.giphy.com/media/FVbsOFYqdARtS/giphy.gif)
> Added global colors and responsive fonts. Example in hoved.html

- SITnett/graphics/style.css
- SITnett/templates/medlemmer/medlemmer.html
- SITnett/templates/meny.html
- SITnett/templates/produksjoner/produksjoner.html
Ferdig med styling av produksjonskort. Tenker det kan merges inn nå så det blir tilgjengelig for dere :)
Kommer til å fortsette med å standardisere kortene så de brukes til medlemmer også :)
> Reusable components

- SITnett/graphics/style.css
- SITnett/templates/info.html
- SITnett/templates/medlemmer/erfaring_fjern.html
- SITnett/templates/medlemmer/medlem_ny.html
- SITnett/templates/medlemmer/medlem_redi.html
- SITnett/templates/medlemmer/medlem_slett.html
- SITnett/templates/medlemmer/utmerkelse_fjern.html
- SITnett/templates/produksjoner/forestilling_fjern.html
- SITnett/templates/produksjoner/produksjon_ny.html
- SITnett/templates/produksjoner/produksjon_redi.html
- SITnett/templates/produksjoner/produksjon_slett.html
Lett styling på skjemaene. 
Oppdaterer knappene når styling for dem er lagt inn.
> Styled forms

- SITnett/graphics/style.css
- SITnett/templates/hoved.html
- SITnett/templates/info.html
- SITnett/templates/kontakt.html
- SITnett/templates/medlemmer/medlemmer.html
- SITnett/templates/meny.html
- SITnett/templates/opptak.html
- SITnett/templates/produksjoner/produksjoner.html
La til gif's og link til skrift på sider som ikke er ferdig, og skjulte det innholdet som ikke er klart enda.
> Under construction

- .gitignore
- SITnett/SITnett/settings.py
Dette må til for at siden skal funke på serveren.
> Support running in production and keep local settings as fallback

- SITnett/SITnett/settings.py
> Allow sit.samfundet.no as host

- SITnett/graphics/style.css
- SITnett/templates/hoved.html
- SITnett/templates/medlemmer/medlemmer.html
- SITnett/templates/produksjoner/produksjoner.html
Har byttet ut flexbox med CSS grid i listevisningene våre. 
Elementene sentrerer seg på siden og det blir overall penere ✨
> List update

- .gitignore
Ignorerer alle lokale filer, slik at du slipper mas fra git hver gang du oppdaterer din egen testdatabase.
> Ignore files folder

- SITnett/graphics/style.css
- SITnett/templates/hoved.html
- SITnett/templates/kontakt.html
- SITnett/templates/medlemmer/medlemmer.html
- SITnett/templates/opptak.html
- SITnett/templates/produksjoner/produksjoner.html
Søknadsteksten er på plass. Må ut i prod så fort som mulig 🏃‍♀️
> Added opptak

- SITnett/graphics/style.css
> fix hero on small mobile screens

- SITnett/templates/hoved.html
Opptaket er åpnet, noe hjemmesiden burde reflektere 😊
> Update hero heading

- SITnett/SITdata/skrift_transfers.py
- SITnett/SITnett/views.py
> Set default os variable to run django script from command line

- SITnett/graphics/style.css
- SITnett/templates/kontakt.html
- SITnett/templates/meny.html
Pynte litt på kontaktlista, og kalle den Lommelista for interne
> Kontakt styling

- docs/installing_packages.md
Endret `python sit/manage.py runserver` til `python SITnett/manage.py runserver` i installing_packages.md
> corrected manage.py directory

- SITnett/SITdata/forms.py
- SITnett/SITnett/views.py
- SITnett/graphics/style.css
- SITnett/templates/medlemmer/medlemmer.html
- SITnett/templates/produksjoner/produksjoner.html
> Production search

- SITnett/SITdata/forms.py
- SITnett/SITnett/views.py
- SITnett/templates/medlemmer/erfaring_fjern.html
- SITnett/templates/medlemmer/medlemmer.html
- SITnett/templates/medlemmer/utmerkelse_fjern.html
- SITnett/templates/produksjoner/anmeldelse_fjern.html
- SITnett/templates/produksjoner/forestilling_fjern.html
- SITnett/templates/produksjoner/produksjoner.html
> Fix 500 error for anon. users on show info page

- SITnett/SITnett/views.py
> Check if user is authenticated before acessing user info

- SITnett/SITdata/admin.py
- SITnett/SITnett/settings.py
> 3, 2, 1, prod!

- .gitignore
- SITnett/SITnett/settings.py
Tar vare på feilmeldinger i en fil på siden. Klientfeil (f.eks. en request til en side som ikke eksisterer eller til en side hvor brukeren ikke har tilgang) lagres i `logs/warnings.txt`, serverfeil (ting som er vår skyld) lagres i `logs/errors.txt`.
> Configure logging

- SITnett/graphics/style.css
- SITnett/templates/produksjoner/produksjon_info.html
> Quick and dirty media player

- .gitignore
- SITnett/graphics/style.css
- SITnett/templates/produksjoner/produksjon_info.html
> Now with VIDEO

- SITnett/graphics/mobile_contact_form.css
- SITnett/graphics/style.css
- SITnett/templates/kontakt.html
- SITnett/templates/meny.html
Sjekk gjerne at det ser OK ut lokalt, spesielt om dere har registrert en del verv i deres lokale database ☺️
> Gjør kontaktskjema enklere på mobil

- SITnett/templates/Lommelista.html
- SITnett/templates/kontakt.html
Add thead and tbody tags to kontakt and Lommelista. Add CSS header block in Lommelista too.
> Add table tags (thead/tbody) and CSS to kontakt and Lommelista.

- SITnett/SITnett/views.py
- SITnett/templates/opptak.html
Fiksa opptakssida slik at den nå sjekker om feltene 'opptaksstart', 'soknadsfrist' og 'opptaksbilde_annet' er fylt før den prøver å hente data herfra.
> Add checks for deadlines and pictures.

- SITnett/SITnett/settings.py
> Disable logging

- SITnett/graphics/admin/css/base.css
- SITnett/graphics/admin/css/nav_sidebar.css
- SITnett/graphics/css/baseline.css
- SITnett/graphics/css/fonts.css
- SITnett/graphics/mobile_contact_form.css
- SITnett/graphics/style.css
- SITnett/logs/warnings.txt
- SITnett/templates/ar/ar_info.html
- SITnett/templates/hoved.html
- SITnett/templates/info.html
- SITnett/templates/medlemmer/medlemmer.html
- SITnett/templates/opptak.html
- SITnett/templates/produksjoner/produksjoner.html
> Css baseline

- SITnett/graphics/style.css
- SITnett/templates/opptak.html
Gjorde en kjapp fiks på knappen på opptaksiden, og la til én til under tekstene.
> Button fix

- SITnett/templates/meny.html
Slo sammen to knapper i footeren!
> Merge footer buttons

- SITnett/SITdata/skrift_transfers.py
- SITnett/SITnett/views.py
- SITnett/templates/produksjoner/produksjon_info.html
Enkel og elegant visehefteknapp. Sjekk om forestillinger er ferdige før man viser billettlink.
> Display visehefte

- SITnett/SITnett/views.py
- SITnett/templates/numre/nummer_info.html
- SITnett/templates/numre/numre.html
- SITnett/templates/produksjoner/produksjon_info.html
Fin ny nummervisning! Jeg la inn en link til den tilhørende produksjonen, og gjorde det også sånn at seksjonen "Kommentar" ikke dukker opp hvis det ikke er lagt inn noen kommentarer til nummeret, så det ikke står en ensom tittel nederst da.
> Remove section "Kommentar" conditionally and add link to Produksjon

- SITnett/SITdata/models.py
- SITnett/SITnett/views.py
> Minor cleanup: Convert comments to docstrings, minor spacing and typing
